modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="logo.png"
description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="computercraft"
    mandatory=true
    # 兼容所有 Forge 1.20.1 的 CC: Tweaked 版本（官方 1.20.1 分支 v1.20.1-1.105.0 ~ 1.120.2）
    # 本模组仅使用 CC:T 多年稳定公开 API（IPeripheral/LuaFunction/ComputerSide 等），无版本特有接口
    versionRange="[1.105.0,)"
    ordering="NONE"
    side="BOTH"